#!/bin/bash

ACTION="$1"

case "$ACTION" in
    "to")
        DEST="$2"
        MSG="$3"
        tpb sms send --to "$DEST" --message "$MSG"
        ;;
    "from")
        SRC="$2"
        tpb sms list --name "$SRC"
        ;;
    "urls")
        SRC="$2"
        tpb --jsv sms list --name "$SRC" |
        tac |
        jq -r \
            'select(.direction == "incoming") | .body' |
        grep -Eo 'https?://[^[:space:]]+'
        ;;
    ""|"threads")
        tpb sms threads
        ;;
    *)
        echo "Unknown action" "$ACTION" >&2
        exit 1
        ;;
esac
